# Generated by Django 2.2.6 on 2019-10-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myawwards', '0004_auto_20191021_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(max_length=255),
        ),
    ]
