# Generated by Django 2.2.6 on 2019-10-21 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myawwards', '0006_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='post_rated',
            new_name='post',
        ),
    ]
