# Generated by Django 2.2.6 on 2019-10-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myawwards', '0008_auto_20191021_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='technologies',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
